server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fridgemarket
    username: root
    password: donghwan02
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 632004548603-h5lqanfbt814qqacdfsuu72jht3mtnnb.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
            client-name: Google
          kakao:
            client-id: c391c0c73e619fff53d865b90bc93bf0
            client-secret: Wo0CBRhjD3IAtzGVO7HkAtcdW5kPfhPQ
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



