server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fridgemarket?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true # 전체 URL 포함
    username: root
    password: soojong9627
    driver-class-name: com.mysql.cj.jdbc.Driver # <-- 이 부분을 여기에 추가/확인!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 632004548603-h5lqanfbt814qqacdfsuu72jht3mtnnb.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: c391c0c73e619fff53d865b90bc93bf0
            client-secret: Wo0CBRhjD3IAtzGVO7HkAtcdW5kPfhPQ
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/kakao/callback
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id

sns:
  google:
    client:
      id: 632004548603-h5lqanfbt814qqacdfsuu72jht3mtnnb.apps.googleusercontent.com
      secret: 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
    callback:
      url: http://localhost:8080/login/oauth2/code/google
    token:
      url: https://oauth2.googleapis.com/token
    url: https://accounts.google.com/o/oauth2/v2/auth
    sns_base_url: https://www.googleapis.com/oauth2/v3/userinfo